# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Damien's Blog
subtitle: Record stories in life, and details in study and work
name: Damien
email: jyh91517@gamil.com
location: Glasgow, Scotland
description: 本站是damien的博客, 内容涵盖生活故事、Java后端技术、Spring Boot、Spring Cloud、微服务架构、大数据演进、高可用架构、中间件使用、系统监控等相关的研究与知识分享。
keywords: damien, MongoDB, Jvm, Docker, data science, open-source, Developer,Programmer, Coder, Java, Python,
encoding: "utf-8"
favicon: favicon.ico 

repository: damien0x0023/damien0x0023.github.io
github_url: https://github.com/damien0x0023
url: https://damien0x0023.github.io
## enforce_ssl: damien0x0023.com

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:

  # -
  #   href: http://favorites.ren/stock.html
  #   label: 股票
  #   target: _blank  

  -
    href: /money.html
    label: Business
    target: _self   

  # -
  #   href: /it.html
  #   label: 深度L
  #   target: _self

  -
    href: /life.html
    label: Life
    target: _self

  # -
  #   href: /arch.html
  #   label: 架构
  #   target: _self

  # -
  #   href: /link.html
  #   label: 友链
  #   target: _self

  -
    href: /about.html
    label: about me
    target: _self

# Navigation. main menu list
navs:

  -
    href: /
    label: Home

  # -
  #   href: /cartoon.html
  #   label: Cartoon
  #   target: _self

  -
    href: /notes.html
    label: Notes
    target: _self

  # -
  #   href: /spring-boot.html
  #   label: Spring Boot
  #   target: _self
  #   subnav:

  #     -
  #       subHref: /spring-boot.html
  #       subLabel: Spring Boot

  #     -
  #       subHref: /spring-cloud.html
  #       subLabel: Spring Cloud

  # -
  #   href: http://www.justdojava.com
  #   label: Java
  #   target: _blank
  #   subnav:

  #     -
  #       subHref: /java.html
  #       subLabel: Jvm 系列文章
        
  #     -
  #       subHref: http://www.justdojava.com
  #       subLabel: Java 极客技术
  #       target: _blank

  # -
    
  #   href: /python.html
  #   label: Python
  #   subnav:

  #     -
  #       subHref: /python.html
  #       subLabel: Python 教程
        
  #     -
  #       subHref: http://www.justdopython.com
  #       subLabel: Python 技术
  #       target: _blank

  -
    href: /archives.html
    label: Archives
    target: _self



# labels. my blog key words
labels:

  # -
  #   href: /payment.html
  #   label: Pay     
  #   target: _self

  # -
  #   href: /fastdfs.html
  #   label: FastDFS
  #   target: _blank

  # -
  #   href: /mongodb.html
  #   label: MongoDB
  #   target: _blank

  # -
  #   href: /docker.html
  #   label: Docker
  #   target: _blank

  -
    href: /open-source.html
    label: Code  
    target: _blank

  # -
  #   href: /gitchat.html
  #   label: Chat
  #   target: _blank


# selected articles
classes:

  # -
  #   href: /cartoon.html
  #   name: 不会笑青年
  #   describe: 内心沉稳 ，放荡不羁。

  -
    href: /life.html
    name: Life story
    describe: Life is a series of story, which is worth living

  -
    href: /it.html
    name: IT industry
    describe: Figures, events and trends in IT




# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 0x0023
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: damien0x0023
    repo: blog-comments
    oauth:
        client_id: 61bfc53d957e74e78f8f
        client_secret: 31c61e66cdcc9ada8db2267ee779d0bdafac434c
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: damien0x0023
    repo: blog-comments
    clientID: 63f31120b9978ee47925
    clientSecret: f40ff7d8fede547487ac5499c797749d73808f5a
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true
